### ISSUE TITLE
Test-OnlineFast.ps1

### ISSUE THREAD

**Issue by IDWBE** [BanterBoy/scripts-blog#15]
when I use this script to scan a subnet with the extra for a range scan

$iprange = 1..255 | ForEach-Object { "10.54.2.$_" }

I don't get the full IP address but get dots when there are 3 digits in the last octet of the IP address. It works fine when you have more then 1 digit in the third octet of the IP address.

Address    Online DNSName                      Status...........
-------    ------ -------                                 -----------------
10.54.2.1    True                                          Success
10.54.2.17   True xyz.domainname		   Success
10.54.2.18   True abc.domainname		   Success
10.54.2.9    True                                          Success
10.54.2.13   True                                         Success
10.54.2.21   True                                         Success
10.54.2...     True                                          Success
10.54.2.5    True                                          Success
10.54.2.10  False                                      Request Timed Out
10.54.2...  False                              Request Timed Out
10.54.2...  False                              Request Timed Out
10.54.2...  False                              Request Timed Out

How can I get the full IP address?

Thanks for your help, I love the script.

**Comment by trossr32** [comment]
@IDWBE I don't think this is anything to do with how many integers are in each octet. Easiest fix would be to pipe your results into an autosized format table, e.g. change the end of the script to this:

```
Get-WmiObject -Class Win32_PingStatus -Filter "(Address='$query') and timeout=$TimeoutMillisec" |
Select-Object -Property Address, $IsOnline, $DNSName, $statusFriendlyText |
Format-Table -AutoSize
```

@BanterBoy will leave this open for now in case you want to add the Format-Table to the script, otherwise I think this can be closed.

**Comment by trossr32** [comment]
@BanterBoy Actually I think the end block should be changed to the following so the script will work for Powershell versions above and below 6:

```
end {
    # convert list of computers into a WMI query string
    $query = $bucket -join "' or Address='"
    
    $collection = $null

    if ($PSVersionTable.PSVersion.Major -ge 6) {
        $collection = Get-CimInstance -ClassName Win32_PingStatus -Filter "(Address='$query') and timeout=$TimeoutMillisec"
    }
    else {
        $collection = Get-WmiObject -Class Win32_PingStatus -Filter "(Address='$query') and timeout=$TimeoutMillisec"
    }

    $collection |
    Select-Object -Property Address, $IsOnline, $DNSName, $statusFriendlyText |
    Format-Table -AutoSize
}
```

**Comment by IDWBE** [comment]
with the adjusted end block it works great

Thanks a lot
